const fs = require('fs');
const path = require('path');

const url = process.env['SUPABASE_URL'] || '';
const key = process.env['SUPABASE_ANON_KEY'] || '';

if (!url || !key) {
  console.warn('[set-env] SUPABASE_URL or SUPABASE_ANON_KEY not set — using empty strings');
}

const content = `// Auto-generated by scripts/set-env.js — do not edit
export const environment = {
  supabaseUrl: '${url}',
  supabaseKey: '${key}',
};
`;

const dir = path.join(__dirname, '..', 'src', 'environments');
fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(path.join(dir, 'environment.ts'), content);
console.log('[set-env] environment.ts written');
